version: '3'
services:
    publisher:
        build: .
        volumes:
            - ./publisher/target:/home/zmq
        command: ["java", "-jar", "/home/zmq/publisher.jar"]


    subscriber:
        build: .
        volumes:
            - ./subscriber/target:/home/zmq
        command: ["java", "-jar", "/home/zmq/subscriber.jar"]
        ports:
          - 5555:5555
        links:
          - publisher